<?php
/*
* $Id: xoops_version.php
* Module: XMAIL
* Version: v2.0
* Release Date: 18 Março 2005
* Author: Claudia Antonini Vitiello Callegari   Gilberto G. de Oliveira (Giba)
* License: GNU
*/

$modversion['name'] = _MI_XMAIL_NAME;
$modversion['version'] = 2.0;
$modversion['description'] = _MI_XMAIL_DESC;
$modversion['author'] = 'Claudia A. V. Callegari';
$modversion['credits'] = 'http://www.xoopstotal.com.br';
//$modversion['help'] = "";
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/logo-xmail.png';
$modversion['dirname'] = 'xmail';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/xmail.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'xmail_mensage';
$modversion['tables'][1] = 'xmail_send_log';
$modversion['tables'][2] = 'xmail_param';
$modversion['tables'][3] = 'xmail_files';
$modversion['tables'][4] = 'xmail_men_anexo';
$modversion['tables'][5] = 'xmail_ativacao';
$modversion['tables'][6] = 'xmail_aux_send';
$modversion['tables'][7] = 'xmail_aux_send_l';
$modversion['tables'][8] = 'xmail_newsletter';
$modversion['tables'][9] = 'xmail_perfil_news';
$modversion['tables'][10] = 'xmail_tabperfil';

// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = '';
$modversion['search']['func'] = '';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_XMAIL_SMNAME1;
$modversion['sub'][1]['url'] = 'submit.php?op=add';
$modversion['sub'][2]['name'] = _MI_XMAIL_SMNAME2;
$modversion['sub'][2]['url'] = 'gerencia.php';
$modversion['sub'][3]['name'] = _MI_XMAIL_ADMENU3;
$modversion['sub'][3]['url'] = 'verlog.php';

// Templates      alterar os nomes  p/  xmail
$modversion['templates'][1]['file'] = 'xmail_mensage.htm';
$modversion['templates'][1]['description'] = 'Mostra mensagens ';
$modversion['templates'][2]['file'] = 'xmail_verlog.htm';
$modversion['templates'][2]['description'] = 'Mostra log de envio de mensagens';
$modversion['templates'][3]['file'] = 'xmail_lote.htm';
$modversion['templates'][3]['description'] = 'Mostra log de envio de mensagens';
$modversion['templates'][4]['file'] = 'xmail_unsub.html';
$modversion['templates'][4]['description'] = 'Cancelar assinatura newsletter';
$modversion['templates'][5]['file'] = 'xmail_subscr.html';
$modversion['templates'][5]['description'] = 'Assinar newsletter';

$modversion['templates'][6]['file'] = 'xmail_notice.html';
$modversion['templates'][6]['description'] = 'newsletter ';

$modversion['templates'][7]['file'] = 'xmail_index.html';
$modversion['templates'][7]['description'] = 'newsletter ';

// Comments
$modversion['hasComments'] = 0;
$modversion['comments']['pageName'] = '';
$modversion['comments']['itemName'] = '';

// blocks
$modversion['blocks'][1]['file'] = 'block_xmail.php';
$modversion['blocks'][1]['name'] = _MI_XMAIL_BLOCK1;
$modversion['blocks'][1]['description'] = _MI_XMAIL_DESCRIBLOCK1;
$modversion['blocks'][1]['show_func'] = 'b_xmail_show_ativa';
$modversion['blocks'][1]['edit_func'] = 'b_xmail_edit_ativa';
//$modversion['blocks'][1]['options'] = "5|0|1|1|1";

$modversion['blocks'][2]['file'] = 'block_xmail.php';
$modversion['blocks'][2]['name'] = _MI_XMAIL_BLOCK2;
$modversion['blocks'][2]['description'] = _MI_XMAIL_DESCRIBLOCK2;
$modversion['blocks'][2]['show_func'] = 'b_xmail_show_news';
$modversion['blocks'][2]['edit_func'] = 'b_xmail_edit_news';
$modversion['blocks'][2]['template'] = 'xmail_block_subcr.html';

//$modversion['blocks'][2]['options'] = "5|0|1|1|1";

$modversion['onInstall'] = 'installscript.php';




